"""Lägg till distans i CardioLog

Revision ID: 5db5f9401ea7
Revises: ac8075e9c2d5
Create Date: 2025-07-21 22:57:47.042615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db5f9401ea7'
down_revision = 'ac8075e9c2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardio_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardio_log', schema=None) as batch_op:
        batch_op.drop_column('distance_km')

    # ### end Alembic commands ###
