"""Ändra duration till sekunder

Revision ID: 7932605e2c58
Revises: 5db5f9401ea7
Create Date: 2025-07-21 21:30:11.720230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7932605e2c58'
down_revision = '5db5f9401ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardio_log', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes', new_column_name='duration_seconds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cardio_log', schema=None) as batch_op:
        batch_op.alter_column('duration_seconds', new_column_name='duration_minutes')

    # ### end Alembic commands ###
