"""Lägg till grams och base_servings i FoodLog

Revision ID: ac8075e9c2d5
Revises: ea5f8eeaa6ae
Create Date: 2025-07-21 22:56:05.866653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8075e9c2d5'
down_revision = 'ea5f8eeaa6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grams', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('base_servings_info', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_log', schema=None) as batch_op:
        batch_op.drop_column('base_servings_info')
        batch_op.drop_column('grams')

    # ### end Alembic commands ###
