"""Skapar weight_log-tabell

Revision ID: ee7b0f15ac1d
Revises: 1569f4b92f5c
Create Date: 2025-07-20 20:09:31.660100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7b0f15ac1d'
down_revision = '1569f4b92f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_log_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_log_date'))

    op.drop_table('weight_log')
    # ### end Alembic commands ###
